name: 'Grace Innovation '
favicon: null
layout_spectrum: 0.01443
typography_spectrum: 0.36529
title: 'Grace Innovation '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8c5ed6'
    - '#002958'
    - '#0f9d58'
    - '#ca2f25'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
