name: 'Grace Innovation '
favicon: null
layout_spectrum: 0.12162124342285097
typography_spectrum: 0.3009756177198142
title: 'Grace Innovation '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5555802555754781
  lightness: 0.06039379024878144
  saturation: 0.46089923568069935
  rhythmicContrast: 0.8913076512981206
purpose: []
